name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Linux Get dependencies
        run: sudo apt install -y cpanminus luarocks valgrind

      - name: Linux Before install
        run: |
          sudo luarocks install luacheck
          luacheck -q .
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

      - name: Linux Install
        run: |
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends openresty

      - name: Linux Script
        run: |
          export PATH=$PATH:/usr/local/openresty/nginx/sbin
          export TEST_NGINX_BINARY=openresty
          openresty -V
          prove -r t
          bash test_with_valgrind.sh
